### PR TITLE
Add support for numerous new syntaxes.

### PR DESCRIPTION
**Pull request by roife**
- d0184b5 https://www.moonbitlang.cn/weekly-updates/2024/01/08/weekly-01-08#1-正式移除-interface-关键字
- a341d81 https://www.moonbitlang.cn/weekly-updates/2024/01/22/weekly-01-22#3-正式移除-var-id--expr-的语法
- 57ce785 In fact, moonbit does not support power operator
- 471614c https://www.moonbitlang.cn/weekly-updates/2024/01/29/weekly-01-29#2-新增管道运算符
- 8e9f9db https://www.moonbitlang.cn/weekly-updates/2024/01/15/weekly-01-15#1-放宽了match的右手侧的语法允许单个语句的出现现在允许下面的写法
- 8d40fec https://www.moonbitlang.cn/weekly-updates/2024/01/22/weekly-01-22#1-新增矩阵函数的语法糖
- 6b7b3cb https://www.moonbitlang.cn/weekly-updates/2024/01/22/weekly-01-22#4-增加了新的关键词-test
- 2f04ab0 https://www.moonbitlang.cn/weekly-updates/2024/01/22/weekly-01-22#2-新增使用-t--构造结构体的语法
- 95dda23 https://www.moonbitlang.cn/weekly-updates/2024/02/05/weekly-02-05#2-新增函数式的loop循环
- 61d2128 Support for `===` operator

### CODE REVIEW

**Comment by roife** [comment]
In the next PR, I will further implement:
1. The implementation of raw string literals, which is relatively complex.
2. The update on 0304.

It seems that there is still controversy in the community regarding the `for` keyword, so I have not implemented it here.

**Comment by roife** [comment]
btw, in the recent update, I saw that the `while_continue_block` was removed. Have they been removed from syntax? (Since the compiler has not updated it yet)

**Comment by tonyfettes** [comment]
Yes, they have been removed.

**Review by tonyfettes — APPROVED** [review]
lgtm

**Comment by tonyfettes** [comment]
@bzy-debug sync `parser.mly` to `moonbit-docs` sometimes next week?

**Pull request merged**
