### PR TITLE
feat: support asi for pipe operator

### PR DESCRIPTION
**Pull request by tonyfettes**
should solve broken pipe expression in #23

### CODE REVIEW

**Comment by bzy-debug** [comment]
This looks like a specific asi hack for pipe operator. Is it possible to implement full asi logic in `scanner.c`?

**Comment by tonyfettes** [comment]
Ideally a general asi should look like this:

```c
// ...
else if (valid_symbols[ASI_SENSITIVE_TOKEN] || ... /* other tokens that are disallowed after semi */) {
  while (iswspace(lexer->lookahead)) {
    skip(lexer);
  }
  if (lexer->lookahead == '/') {
    lexer->result_symbol = COMMENT;
    // handle comment
  } else if (lexer->lookahead == '|') {
    lexer->result_symbol = PIPE_OPERATOR;
    // handle pipeline
  } else if (/* handle other cases */) {
    // ...
  }
}
```

**Comment by roife** [comment]
https://taolun.moonbitlang.cn/t/topic/444#h-5-6

Considering the issues described in this link, maybe we still need a real ASI for more robust parsing

**Comment by tonyfettes** [comment]
This asi is much looser that compiler parser (the one used in online IDE, VS Code plugin, and compiler).

For example, it accepts

```
fn init {
  let x = 3
|>
4
}
```

and

```
fn init {
s
.
y
}
```

which would be rejected by the compiler paser.

**Pull request merged**
